export const actionTypesLogin = {
  USER_LOGIN_LOADING: "USER_LOGIN_LOADING",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_ERROR: "USER_LOGIN_ERROR",
};

export const actionTypesRegister = {
  USER_REGISTER_LOADING: "USER_REGISTER_LOADING",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_ERROR: "USER_REGISTER_ERROR",
};

export const actionTypesEmailVerify = {
  USER_EMAILVERIFY_LOADING: "USER_EMAILVERIFY_LOADING",
  USER_EMAILVERIFY_SUCCESS: "USER_EMAILVERIFY_SUCCESS",
  USER_EMAILVERIFY_ERROR: "USER_EMAILVERIFY_ERROR",
};

export const actionTypesPhoneNoVerify = {
  USER_PHONENOVERIFY_LOADING: "USER_PHONENOVERIFY_LOADING",
  USER_PHONENOVERIFY_SUCCESS: "USER_PHONENOVERIFY_SUCCESS",
  USER_PHONENOVERIFY_ERROR: "USER_PHONENOVERIFY_ERROR",
};

export const actionTypesForgotPassword = {
  USER_FORGOTPASSWORD_LOADING: "USER_FORGOTPASSWORD_LOADING",
  USER_FORGOTPASSWORD_SUCCESS: "USER_FORGOTPASSWORD_SUCCESS",
  USER_FORGOTPASSWORD_ERROR: "USER_FORGOTPASSWORD_ERROR",
};


export const actionTypesForgotPasswordReset = {
  USER_FORGOTPASSWORDRESET_LOADING: "USER_FORGOTPASSWORDRESET_LOADING",
  USER_FORGOTPASSWORDRESET_SUCCESS: "USER_FORGOTPASSWORDRESET_SUCCESS",
  USER_FORGOTPASSWORDRESET_ERROR: "USER_FORGOTPASSWORDRESET_ERROR",
};

export const actionTypesResendEmailOtp = {
  RESENDEMAILOTP_LOADING: "RESENDEMAILOTP_LOADING",
  RESENDEMAILOTP_SUCCESS: "RESENDEMAILOTP_SUCCESS",
  RESENDEMAILOTP_ERROR: "RESENDEMAILOTP_ERROR",
};

export const actionTypesResendPhoneNoOtp = {
  RESENDPHONENO_OTP_LOADING: "RESENDPHONENO_OTP_LOADING",
  RESENDPHONENO_OTP_SUCCESS: "RESENDPHONENO_OTP_SUCCESS",
  RESENDPHONENO_OTP_ERROR: "RESENDPHONENO_OTP_ERROR",
};

