export const actionTypesCreateChat = {
  CREATE_CHAT_LOADING: "CREATE_CHAT_LOADING",
  CREATE_CHAT_SUCCESS: "CREATE_CHAT_SUCCESS",
  CREATE_CHAT_ERROR: "CREATE_CHAT_ERROR",
};

export const actionTypesChatList = {
  CHAT_LIST_LOADING: "CHAT_LIST_LOADING",
  CHAT_LIST_SUCCESS: "CHAT_LIST_SUCCESS",
  CHAT_LIST_ERROR: "CHAT_LIST_ERROR",
};

export const actionTypesChatImage = {
  CHAT_IMAGE_LOADING: "CHAT_IMAGE_LOADING",
  CHAT_IMAGE_SUCCESS: "CHAT_IMAGE_SUCCESS",
  CHAT_IMAGE_ERROR: "CHAT_IMAGE_ERROR",
};
