export const actionTypesCompletedOrders = {
  COMPLETED_ORDERS_LOADING: "COMPLETED_ORDERS_LOADING",
  COMPLETED_ORDERS_SUCCESS: "COMPLETED_ORDERS_SUCCESS",
  COMPLETED_ORDERS_ERROR: "COMPLETED_ORDERS_ERROR",
};
