export const actionTypesFavs = {
  FAVS_LIST_LOADING: "FAVS_LIST_LOADING",
  FAVS_LIST_SUCCESS: "FAVS_LIST_SUCCESS",
  FAVS_LIST_ERROR: " FAVS_LIST_ERROR",
  FAVS_LIST_MORE_ERROR: " FAVS_LIST_MORE_ERROR",
  FAVS_LIST_ENDS: " FAVS_LIST_ENDS",
  FAVS_LIST_MORE_LOADING: "FAVS_LIST_MORE_LOADING",
};
