export const actionTypesLocationPermission = {
  // LOCATION_PERMISSION_LOADING: "LOCATION_PERMISSION_LOADING",
  LOCATION_PERMISSION_SUCCESS: "LOCATION_PERMISSION_SUCCESS",
  LOCATION_PERMISSION_ERROR: "LOCATION_PERMISSION_ERROR",
};
