export const actionTypesLike = {
  LIKE_LOADING: "LIKE_LOADING",
  LIKE_SUCCESS: "LIKE_SUCCESS",
  LIKE_ERROR: " LIKE_ERROR",
};

export const actionTypeCommentLike = {
  COMMENT_LIKE_LOADING: "COMMENT_LIKE_LOADING",
  COMMENT_LIKE_SUCCESS: "COMMENT_LIKE_SUCCESS",
  COMMENT_LIKE_ERROR: " COMMENT_LIKE_ERROR",
};
