export const actionTypesMarkets = {
  FETCH_MARKET_LOADING: "FETCH_MARKET_LOADING",
  FETCH_MARKET_SUCCESS: "FETCH_MARKET_SUCCESS",
  FETCH_MARKET_SUCCESS_MEN: "FETCH_MARKET_SUCCESS_MEN",
  FETCH_MARKET_SUCCESS_WOMEN: "FETCH_MARKET_SUCCESS_WOMEN",
  FETCH_MARKET_SUCCESS_NATIVE: "FETCH_MARKET_SUCCESS_NATIVE",
  FETCH_MARKET_SUCCESS_ANKARA: "FETCH_MARKET_SUCCESS_ANKARA",
  FETCH_MARKET_ERROR: " FETCH_MARKET_ERROR",
  FETCH_MARKET_MORE_ERROR: " FETCH_MARKET_MORE_ERROR",
  FETCH_MARKET_ENDS: " FETCH_MARKET_ENDS",
  FETCH_MARKET_MORE_LOADING: "FETCH_MARKET_MORE_LOADING",
  FETCH_MARKET_CATEGORY: "FETCH_MARKET_CATEGORY",
};
export const actionTypesCreateMarket = {
  CREATE_MARKET_LOADING: "CREATE_MARKET_LOADING",
  CREATE_MARKET_SUCCESS: "CREATE_MARKET_SUCCESS",
  CREATE_MARKET_ERROR: " CREATE_MARKET_ERROR",
};

export const actionTypesAddToCart = {
  ADD_TO_CART_LOADING: "ADD_TO_CART_LOADING",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_ERROR: " ADD_TO_CART_ERROR",
};
export const actionTypesCartView = {
  CART_VIEW_LOADING: "CART_VIEW_LOADING",
  CART_VIEW_SUCCESS: "CART_VIEW_SUCCESS",
  CART_EMPTY_SUCCESS: "CART_EMPTY_SUCCESS",
  CART_VIEW_ERROR: " CART_VIEW_ERROR",
};
export const actionTypesCheckOut = {
  CHECK_OUT_LOADING: "CHECK_OUT_LOADING",
  CHECK_OUT_SUCCESS: "CHECK_OUT_SUCCESS",
  CHECK_OUT_ERROR: " CHECK_OUT_ERROR",
};
export const actionTypesGetOrders = {
  GET_ORDERS_LOADING: "GET_ORDERS_LOADING",
  GET_ORDERS_SUCCESS: "GET_ORDERS_SUCCESS",
  GET_ORDERS_ERROR: " GET_ORDERS_ERROR",
};
export const actionTypesTrackorder = {
  TRACK_ORDER_LOADING: "TRACK_ORDER_LOADING",
  TRACK_ORDER_SUCCESS: "TRACK_ORDER_SUCCESS",
  TRACK_ORDER_ERROR: " TRACK_ORDER_ERROR",
};

export const actionTypesTrackStatus = {
  TRACK_ORDER_STATUS_LOADING: "TRACK_ORDER_STATUS_LOADING",
  TRACK_ORDER_STATUS_SUCCESS: "TRACK_ORDER_STATUS_SUCCESS",
  TRACK_ORDER_STATUS_ERROR: " TRACK_ORDER_ERROR",
};
