export const actionTypesNotification = {
  NOTIFICATION_LOADING: "NOTIFICATION_LOADING",
  NOTIFICATION_SUCCESS: "NOTIFICATION_SUCCESS",
  NOTIFICATION_ERROR: "NOTIFICATION_ERROR",
};

export const actionTypesFeedback = {
  FEED_BACK_LOADING: "FEED_BACK_LOADING",
  FEED_BACK_SUCCESS: "FEED_BACK_SUCCESS",
  FEED_BACK_ERROR: "FEED_BACK_ERROR",
};
