export const actionTypesFeeds = {
  FETCH_FEEDS_LOADING: "FETCH_FEEDS_LOADING",
  FETCH_FEEDS_SUCCESS: "FETCH_FEEDS_SUCCESS",
  FETCH_FEEDS_SUCCESS_MEN: "FETCH_FEEDS_SUCCESS_MEN",
  FETCH_FEEDS_SUCCESS_WOMEN: "FETCH_FEEDS_SUCCESS_WOMEN",
  FETCH_FEEDS_SUCCESS_NATIVE: "FETCH_FEEDS_SUCCESS_NATIVE",
  FETCH_FEEDS_SUCCESS_ANKARA: "FETCH_FEEDS_SUCCESS_ANKARA",
  FETCH_FEEDS_ERROR: " FETCH_FEEDS_ERROR",
  FETCH_FEEDS_MORE_ERROR: " FETCH_FEEDS_MORE_ERROR",
  FETCH_FEEDS_ENDS: " FETCH_FEEDS_ENDS",
  FETCH_FEEDS_MORE_LOADING: "FETCH_FEEDS_MORE_LOADING",
};
export const actionTypesFeedsMen = {
  FETCH_FEEDS_LOADING_MEN: "FETCH_FEEDS_LOADING_MEN",
  FETCH_FEEDS_SUCCESS_MEN: "FETCH_FEEDS_SUCCESS_MEN",
  FETCH_FEEDS_ERROR_MEN: " FETCH_FEEDS_ERROR_MEN",
  FETCH_FEEDS_MORE_ERROR_MEN: " FETCH_FEEDS_MORE_ERROR_MEN",
  FETCH_FEEDS_ENDS_MEN: " FETCH_FEEDS_ENDS_MEN",
  FETCH_FEEDS_MORE_LOADING_MEN: "FETCH_FEEDS_MORE_LOADING_MEN",
};
export const actionTypesFeedsWomen = {
  FETCH_FEEDS_LOADING_WOMEN: "FETCH_FEEDS_LOADING_WOMEN",
  FETCH_FEEDS_SUCCESS_WOMEN: "FETCH_FEEDS_SUCCESS_WOMEN",
  FETCH_FEEDS_ERROR_WOMEN: " FETCH_FEEDS_ERROR_WOMEN",
  FETCH_FEEDS_MORE_ERROR_WOMEN: " FETCH_FEEDS_MORE_ERROR_WOMEN",
  FETCH_FEEDS_ENDS_WOMEN: " FETCH_FEEDS_ENDS_WOMEN",
  FETCH_FEEDS_MORE_LOADING_WOMEN: "FETCH_FEEDS_MORE_LOADING_WOMEN",
};
export const actionTypesFeedsNative = {
  FETCH_FEEDS_LOADING_NATIVE: "FETCH_FEEDS_LOADING_NATIVE",
  FETCH_FEEDS_SUCCESS_NATIVE: "FETCH_FEEDS_SUCCESS_NATIVE",
  FETCH_FEEDS_ERROR_NATIVE: " FETCH_FEEDS_ERROR_NATIVE",
  FETCH_FEEDS_MORE_ERROR_NATIVE: " FETCH_FEEDS_MORE_ERROR_NATIVE",
  FETCH_FEEDS_ENDS_NATIVE: " FETCH_FEEDS_ENDS_NATIVE",
  FETCH_FEEDS_MORE_LOADING_NATIVE: "FETCH_FEEDS_MORE_LOADING_NATIVE",
};
export const actionTypesFeedsAnkara = {
  FETCH_FEEDS_LOADING_ANKARA: "FETCH_FEEDS_LOADING_ANKARA",
  FETCH_FEEDS_SUCCESS_ANKARA: "FETCH_FEEDS_SUCCESS_ANKARA",
  FETCH_FEEDS_ERROR_ANKARA: " FETCH_FEEDS_ERROR_ANKARA",
  FETCH_FEEDS_MORE_ERROR_ANKARA: " FETCH_FEEDS_MORE_ERROR_ANKARA",
  FETCH_FEEDS_ENDS_ANKARA: " FETCH_FEEDS_ENDS_ANKARA",
  FETCH_FEEDS_MORE_LOADING_ANKARA: "FETCH_FEEDS_MORE_LOADING_ANKARA",
};

export const actionTypesAddComment = {
  ADD_COMMENT_LOADING: "ADD_COMMENT_LOADING",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_ERROR: " ADD_COMMENT_ERROR",
};

export const actionTypesAddFavorite = {
  ADD_FAVOURITE_LOADING: "ADD_FAVOURITE_LOADING",
  ADD_FAVOURITE_SUCCESS: "ADD_FAVOURITE_SUCCESS",
  ADD_FAVOURITE_ERROR: " ADD_FAVOURITE_ERROR",
  ITEM_ADDED_TO_FAVOURITE_ALL: " ITEM_ADDED_TO_FAVOURITE_ALL",
  ITEM_ADDED_TO_FAVOURITE_MEN: " ITEM_ADDED_TO_FAVOURITE_MEN",
  ITEM_ADDED_TO_FAVOURITE_WOMEN: " ITEM_ADDED_TO_FAVOURITE_WOMEN",
  ITEM_ADDED_TO_FAVOURITE_NATIVE: " ITEM_ADDED_TO_FAVOURITE_NATIVE",
  ITEM_ADDED_TO_FAVOURITE_ANKARA: " ITEM_ADDED_TO_FAVOURITE_ANKARA",
};

export const actionTypesCreatePost = {
  CREATE_POSTS_LOADING: "CREATE_POSTS_LOADING",
  CREATE_POSTS_SUCCESS: "CREATE_POSTS_SUCCESS",
  CREATE_POSTS_ERROR: " CREATE_POSTS_ERROR",
};

export const actionTypesPostDetail = {
  POST_DETAIL_LOADING: "POST_DETAIL_LOADING",
  POST_DETAIL_SUCCESS: "POST_DETAIL_SUCCESS",
  POST_DETAIL_ERROR: " POST_DETAIL_ERROR",
};
export const actionTypesComment = {
  COMMENT_LIST_LOADING: "COMMENT_LIST_LOADING",
  COMMENT_LIST_SUCCESS: "COMMENT_LIST_SUCCESS",
  COMMENT_LIST_ERROR: " COMMENT_LIST_ERROR",
  COMMENT_LIST_MORE_ERROR: " COMMENT_LIST_MORE_ERROR",
  COMMENT_LIST_ENDS: " COMMENT_LIST_ENDS",
  COMMENT_LIST_MORE_LOADING: "COMMENT_LIST_MORE_LOADING",
};
