export const actionTypesFeeds = {
  FETCH_FEEDS_LOADING: "FETCH_FEEDS_LOADING",
  FETCH_FEEDS_SUCCESS: "FETCH_FEEDS_SUCCESS",
  FETCH_FEEDS_ERROR: " FETCH_FEEDS_ERROR",
  FETCH_FEEDS_MORE_ERROR: " FETCH_FEEDS_MORE_ERROR",
  FETCH_FEEDS_ENDS: " FETCH_FEEDS_ENDS",
  FETCH_FEEDS_MORE_LOADING: " FETCH_FEEDS_MORE_LOADING",
};

export const actionTypesAddComment = {
  ADD_COMMENT_LOADING: "ADD_COMMENT_LOADING",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_ERROR: " ADD_COMMENT_ERROR",
};

export const actionTypesAddFavorite = {
  ADD_FAVOURITE_LOADING: "ADD_FAVOURITE_LOADING",
  ADD_FAVOURITE_SUCCESS: "ADD_FAVOURITE_SUCCESS",
  ADD_FAVOURITE_ERROR: " ADD_FAVOURITE_ERROR",
};

export const actionTypesCreatePost = {
  CREATE_POSTS_LOADING: "CREATE_POSTS_LOADING",
  CREATE_POSTS_SUCCESS: "CREATE_POSTS_SUCCESS",
  CREATE_POSTS_ERROR: " CREATE_POSTS_ERROR",
};
export const actionTypesPostDetail = {
  POST_DETAIL_LOADING: "POST_DETAIL_LOADING",
  POST_DETAIL_SUCCESS: "POST_DETAIL_SUCCESS",
  POST_DETAIL_ERROR: " POST_DETAIL_ERROR",
};
