export const actionTypesFeeds = {
  FETCH_FEEDS_LOADING: "FETCH_FEEDS_LOADING",
  FETCH_FEEDS_SUCCESS: "FETCH_FEEDS_SUCCESS",
  FETCH_FEEDS_ERROR: " FETCH_FEEDS_ERROR",
};



export const actionTypesAddComment = {
  ADD_COMMENT_LOADING: "ADD_COMMENT_LOADING",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_ERROR: " ADD_COMMENT_ERROR",
};


export const actionTypesAddFavorite = {
  ADD_COMMENT_LOADING: "ADD_COMMENT_LOADING",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_ERROR: " ADD_COMMENT_ERROR",
};


