export const actionTypesSelfPosts = {
  SELF_POST_LOADING: "SELF_POST_LOADING",
  SELF_POST_SUCCESS: "SELF_POST_SUCCESS",
  SELF_POST_ERROR: " SELF_POST_ERROR",
  SELF_POST_MORE_ERROR: " SELF_POST_MORE_ERROR",
  SELF_POST_ENDS: " SELF_POST_ENDS",
  SELF_POST_MORE_LOADING: "SELF_POST_MORE_LOADING",
};
export const actionTypesForSale = {
  FOR_SALE_LOADING: "FOR_SALE_LOADING",
  FOR_SALE_SUCCESS: "FOR_SALE_SUCCESS",
  FOR_SALE_ERROR: " FOR_SALE_ERROR",
  FOR_SALE_MORE_ERROR: " FOR_SALE_MORE_ERROR",
  FOR_SALE_ENDS: " FOR_SALE_ENDS",
  FOR_SALE_MORE_LOADING: "FOR_SALE_MORE_LOADING",
};
export const actionTypesSelfLiked = {
  SELF_LIKE_LOADING: "SELF_LIKE_LOADING",
  SELF_LIKE_SUCCESS: "SELF_LIKE_SUCCESS",
  SELF_LIKE_ERROR: " SELF_LIKE_ERROR",
  SELF_LIKE_MORE_ERROR: " SELF_LIKE_MORE_ERROR",
  SELF_LIKE_ENDS: " SELF_LIKE_ENDS",
  SELF_LIKE_MORE_LOADING: "SELF_LIKE_MORE_LOADING",
};
