export const actionTypesReiew = {
  REVIEW_LOADING: "REVIEW_LOADING",
  REVIEW_SUCCESS: "REVIEW_SUCCESS",
  REVIEW_ERROR: " REVIEW_ERROR",
  REVIEW_MORE_ERROR: " REVIEW_MORE_ERROR",
  REVIEW_ENDS: " REVIEW_ENDS",
  REVIEW_MORE_LOADING: "REVIEW_MORE_LOADING",
};

export const actionTypesAddReview = {
  ADD_REVIEW_LOADING: "ADD_REVIEW_LOADING",
  ADD_REVIEW_SUCCESS: "ADD_REVIEW_SUCCESS",
  ADD_REVIEW_ERROR: " ADD_REVIEW_ERROR",
};
