export const actionTypesProductSearch = {
  PRODUCT_SEARCH_LOADING: "PRODUCT_SEARCH_LOADING",
  PRODUCT_SEARCH_MORE_LOADING: "PRODUCT_SEARCH_MORE_LOADING",
  PRODUCT_SEARCH_SUCCESS: "PRODUCT_SEARCH_SUCCESS",
  PRODUCT_SEARCH_ERROR: " PRODUCT_SEARCH_ERROR",
  PRODUCT_SEARCH_MORE_ERROR: " PRODUCT_SEARCH_MORE_ERROR",
};
export const actionTypesLatestSearch = {
  LATEST_SEARCH_LOADING: "LATEST_SEARCH_LOADING",
  LATEST_SEARCH_MORE_LOADING: "LATEST_SEARCH_MORE_LOADING",
  LATEST_SEARCH_SUCCESS: "LATEST_SEARCH_SUCCESS",
  LATEST_SEARCH_ERROR: " LATEST_SEARCH_ERROR",
  LATEST_SEARCH_MORE_ERROR: " LATEST_SEARCH_MORE_ERROR",
};
export const actionTypesPeoleSearch = {
  PEOPLE_SEARCH_LOADING: "PEOPLE_SEARCH_LOADING",
  PEOPLE_SEARCH_MORE_LOADING: "PEOPLE_SEARCH_MORE_LOADING",
  PEOPLE_SEARCH_SUCCESS: "PEOPLE_SEARCH_SUCCESS",
  PEOPLE_SEARCH_ERROR: " PEOPLE_SEARCH_ERROR",
  PEOPLE_SEARCH_MORE_ERROR: " PEOPLE_SEARCH_MORE_ERROR",
};
export const actionTypesPostSearch = {
  POST_SEARCH_LOADING: "POST_SEARCH_LOADING",
  POST_SEARCH_MORE_LOADING: "POST_SEARCH_MORE_LOADING",
  POST_SEARCH_SUCCESS: "POST_SEARCH_SUCCESS",
  POST_SEARCH_ERROR: " POST_SEARCH_ERROR",
  POST_SEARCH_MORE_ERROR: " POST_SEARCH_MORE_ERROR",
};
