

export const sales = [
    {
        id: 1,
        productImage:"",
        productName:"High Quality Caftan",
        designer:"E-Ward Fits",
        rating:"3",
        designerName:"",
        dateOrdered:"",
        dateArrived:"3/7/2015",
        productPrice:"#37,500.00",
        productDescription:"cream average impossible community characteristic depend morning subject worth courage contrast grown slight coast thick mixture pen mill outside opinion production order egg wheat",
        deliveryFee:"#5,000.00",
        totalAmountPaid:"#42,500.00"
    },
    {
        id: 2,
        productImage:"",
        productName:"High Quality Caftan",
        designer:"E-Ward Fits",
        rating:"4",
        designerName:"",
        dateOrdered:"",
        dateArrived:"3/7/2015",
        productPrice:"#37,500.00",
        productDescription:"cream average impossible community characteristic depend morning subject worth courage contrast grown slight coast thick mixture pen mill outside opinion production order egg wheat",
        deliveryFee:"#5,000.00",
        totalAmountPaid:"#42,500.00"
    },
    {
        id: 3,
        productImage:"",
        productName:"High Quality Caftan",
        designer:"E-Ward Fits",
        rating:"4",
        designerName:"",
        dateOrdered:"",
        dateArrived:"3/7/2015",
        productPrice:"#37,500.00",
        productDescription:"cream average impossible community characteristic depend morning subject worth courage contrast grown slight coast thick mixture pen mill outside opinion production order egg wheat",
        deliveryFee:"#5,000.00",
        totalAmountPaid:"#42,500.00"
    },
    {
        id: 4,
        productImage:"",
        productName:"High Quality Caftan",
        designer:"E-Ward Fits",
        rating:"4",
        designerName:"",
        dateOrdered:"",
        dateArrived:"3/7/2015",
        productPrice:"#37,500.00",
        productDescription:"cream average impossible community characteristic depend morning subject worth courage contrast grown slight coast thick mixture pen mill outside opinion production order egg wheat",
        deliveryFee:"#5,000.00",
        totalAmountPaid:"#42,500.00"
    },
    {
        id: 5,
        productImage:"",
        productName:"High Quality Caftan",
        designer:"E-Ward Fits",
        rating:"3",
        designerName:"",
        dateOrdered:"",
        dateArrived:"3/7/2015",
        productPrice:"#37,500.00",
        productDescription:"cream average impossible community characteristic depend morning subject worth courage contrast grown slight coast thick mixture pen mill outside opinion production order egg wheat",
        deliveryFee:"#5,000.00",
        totalAmountPaid:"#42,500.00"
    },
    {
        id: 6,
        productImage:"",
        productName:"High Quality Caftan",
        designer:"E-Ward Fits",
        rating:"2",
        designerName:"",
        dateOrdered:"",
        dateArrived:"3/7/2015",
        productPrice:"#37,500.00",
        productDescription:"cream average impossible community characteristic depend morning subject worth courage contrast grown slight coast thick mixture pen mill outside opinion production order egg wheat",
        deliveryFee:"#5,000.00",
        totalAmountPaid:"#42,500.00"
    },
    {
        id: 7,
        productImage:"",
        productName:"High Quality Caftan",
        designer:"E-Ward Fits",
        rating:"3",
        designerName:"",
        dateOrdered:"",
        dateArrived:"3/7/2015",
        productPrice:"#37,500.00",
        productDescription:"cream average impossible community characteristic depend morning subject worth courage contrast grown slight coast thick mixture pen mill outside opinion production order egg wheat",
        deliveryFee:"#5,000.00",
        totalAmountPaid:"#42,500.00"
    },
]